import { Kanit } from "next/font/google";
import "./globals.css";

const kanitFont = Kanit({
  variable: "--font-kanit",
  subsets: ["latin", "thai"],
  weight: [`100`, `200`, `300`, `400`, `500`, `600`, `700`, `800`, `900`], // เลือกน้ำหนักที่ต้องการ
});

export const metadata = {
  title: "แพลตฟอร์มจองสนามกีฬาออนไลน์",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${kanitFont.variable} antialiased`}>{children}</body>
    </html>
  );
}
